pcall(require, "user/nvim-tree")
pcall(require, "colorschemes")
pcall(require, "settings")
pcall(require, "mappings")
pcall(require, "plugins")
pcall(require, "user/telescope")
pcall(require, "user/bufferline")
pcall(require, "user/nvim-treesitter")
pcall(require, "user/lualine")
pcall(require, "user/alpha-nvim")
pcall(require, "user/toggleterm")
pcall(require, "user/comment")
pcall(require, "user/lsp")
pcall(require, "user/cmp")
pcall(require, "user/bufdel")
pcall(require, "user/nvim-webdev-icons")
pcall(require, "user/rooter")
require('user/dap')
